# Generated by Django 2.1.4 on 2018-12-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='creator',
            new_name='author',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(default='drama', max_length=100),
        ),
    ]
