# Generated by Django 2.2.7 on 2019-11-13 14:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('changed_at', models.DateTimeField(db_index=True, verbose_name='Last modified')),
                ('title', models.CharField(max_length=255)),
                ('task', models.CharField(max_length=255)),
                ('done', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
